// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessages.proto

package io.github.ppissias.xsrpcj.example.performance;

public final class TestMessages {
  private TestMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMessages.MessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestData = 1;</code>
     */
    java.lang.String getRequestData();
    /**
     * <code>string requestData = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestDataBytes();

    /**
     * <code>int32 numberOfCallbacks = 2;</code>
     */
    int getNumberOfCallbacks();
  }
  /**
   * <pre>
   *sample message request
   * </pre>
   *
   * Protobuf type {@code TestMessages.MessageRequest}
   */
  public  static final class MessageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMessages.MessageRequest)
      MessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageRequest.newBuilder() to construct.
    private MessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageRequest() {
      requestData_ = "";
      numberOfCallbacks_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestData_ = s;
              break;
            }
            case 16: {

              numberOfCallbacks_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest.class, io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest.Builder.class);
    }

    public static final int REQUESTDATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestData_;
    /**
     * <code>string requestData = 1;</code>
     */
    public java.lang.String getRequestData() {
      java.lang.Object ref = requestData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestData_ = s;
        return s;
      }
    }
    /**
     * <code>string requestData = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestDataBytes() {
      java.lang.Object ref = requestData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBEROFCALLBACKS_FIELD_NUMBER = 2;
    private int numberOfCallbacks_;
    /**
     * <code>int32 numberOfCallbacks = 2;</code>
     */
    public int getNumberOfCallbacks() {
      return numberOfCallbacks_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestData_);
      }
      if (numberOfCallbacks_ != 0) {
        output.writeInt32(2, numberOfCallbacks_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestData_);
      }
      if (numberOfCallbacks_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numberOfCallbacks_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest)) {
        return super.equals(obj);
      }
      io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest other = (io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest) obj;

      boolean result = true;
      result = result && getRequestData()
          .equals(other.getRequestData());
      result = result && (getNumberOfCallbacks()
          == other.getNumberOfCallbacks());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRequestData().hashCode();
      hash = (37 * hash) + NUMBEROFCALLBACKS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfCallbacks();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *sample message request
     * </pre>
     *
     * Protobuf type {@code TestMessages.MessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMessages.MessageRequest)
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest.class, io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest.Builder.class);
      }

      // Construct using io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestData_ = "";

        numberOfCallbacks_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageRequest_descriptor;
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest getDefaultInstanceForType() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest.getDefaultInstance();
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest build() {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest buildPartial() {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest result = new io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest(this);
        result.requestData_ = requestData_;
        result.numberOfCallbacks_ = numberOfCallbacks_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest) {
          return mergeFrom((io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest other) {
        if (other == io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest.getDefaultInstance()) return this;
        if (!other.getRequestData().isEmpty()) {
          requestData_ = other.requestData_;
          onChanged();
        }
        if (other.getNumberOfCallbacks() != 0) {
          setNumberOfCallbacks(other.getNumberOfCallbacks());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestData_ = "";
      /**
       * <code>string requestData = 1;</code>
       */
      public java.lang.String getRequestData() {
        java.lang.Object ref = requestData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestData = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestDataBytes() {
        java.lang.Object ref = requestData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestData = 1;</code>
       */
      public Builder setRequestData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestData = 1;</code>
       */
      public Builder clearRequestData() {
        
        requestData_ = getDefaultInstance().getRequestData();
        onChanged();
        return this;
      }
      /**
       * <code>string requestData = 1;</code>
       */
      public Builder setRequestDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestData_ = value;
        onChanged();
        return this;
      }

      private int numberOfCallbacks_ ;
      /**
       * <code>int32 numberOfCallbacks = 2;</code>
       */
      public int getNumberOfCallbacks() {
        return numberOfCallbacks_;
      }
      /**
       * <code>int32 numberOfCallbacks = 2;</code>
       */
      public Builder setNumberOfCallbacks(int value) {
        
        numberOfCallbacks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numberOfCallbacks = 2;</code>
       */
      public Builder clearNumberOfCallbacks() {
        
        numberOfCallbacks_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestMessages.MessageRequest)
    }

    // @@protoc_insertion_point(class_scope:TestMessages.MessageRequest)
    private static final io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest();
    }

    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<MessageRequest>() {
      public MessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageRequest> getParserForType() {
      return PARSER;
    }

    public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMessages.MessageResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
     */
    int getResponseValue();
    /**
     * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
     */
    io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum getResponse();
  }
  /**
   * <pre>
   *sample message response
   * </pre>
   *
   * Protobuf type {@code TestMessages.MessageResponse}
   */
  public  static final class MessageResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMessages.MessageResponse)
      MessageResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageResponse.newBuilder() to construct.
    private MessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageResponse() {
      response_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              response_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.class, io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code TestMessages.MessageResponse.responseEnum}
     */
    public enum responseEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACCEPTED = 0;</code>
       */
      ACCEPTED(0),
      /**
       * <code>REJECTED = 1;</code>
       */
      REJECTED(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ACCEPTED = 0;</code>
       */
      public static final int ACCEPTED_VALUE = 0;
      /**
       * <code>REJECTED = 1;</code>
       */
      public static final int REJECTED_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static responseEnum valueOf(int value) {
        return forNumber(value);
      }

      public static responseEnum forNumber(int value) {
        switch (value) {
          case 0: return ACCEPTED;
          case 1: return REJECTED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<responseEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          responseEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<responseEnum>() {
              public responseEnum findValueByNumber(int number) {
                return responseEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final responseEnum[] VALUES = values();

      public static responseEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private responseEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TestMessages.MessageResponse.responseEnum)
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private int response_;
    /**
     * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
     */
    public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
     */
    public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum getResponse() {
      io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum result = io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum.valueOf(response_);
      return result == null ? io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum.ACCEPTED.getNumber()) {
        output.writeEnum(1, response_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum.ACCEPTED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, response_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse)) {
        return super.equals(obj);
      }
      io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse other = (io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse) obj;

      boolean result = true;
      result = result && response_ == other.response_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + response_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *sample message response
     * </pre>
     *
     * Protobuf type {@code TestMessages.MessageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMessages.MessageResponse)
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.class, io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.Builder.class);
      }

      // Construct using io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        response_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_MessageResponse_descriptor;
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse getDefaultInstanceForType() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.getDefaultInstance();
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse build() {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse buildPartial() {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse result = new io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse(this);
        result.response_ = response_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse) {
          return mergeFrom((io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse other) {
        if (other == io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.getDefaultInstance()) return this;
        if (other.response_ != 0) {
          setResponseValue(other.getResponseValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int response_ = 0;
      /**
       * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
       */
      public int getResponseValue() {
        return response_;
      }
      /**
       * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
       */
      public Builder setResponseValue(int value) {
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
       */
      public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum getResponse() {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum result = io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum.valueOf(response_);
        return result == null ? io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
       */
      public Builder setResponse(io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse.responseEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        response_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.TestMessages.MessageResponse.responseEnum response = 1;</code>
       */
      public Builder clearResponse() {
        
        response_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestMessages.MessageResponse)
    }

    // @@protoc_insertion_point(class_scope:TestMessages.MessageResponse)
    private static final io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse();
    }

    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageResponse>
        PARSER = new com.google.protobuf.AbstractParser<MessageResponse>() {
      public MessageResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageResponse> getParserForType() {
      return PARSER;
    }

    public io.github.ppissias.xsrpcj.example.performance.TestMessages.MessageResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CallbackResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMessages.CallbackResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string callbackText = 1;</code>
     */
    java.util.List<java.lang.String>
        getCallbackTextList();
    /**
     * <code>repeated string callbackText = 1;</code>
     */
    int getCallbackTextCount();
    /**
     * <code>repeated string callbackText = 1;</code>
     */
    java.lang.String getCallbackText(int index);
    /**
     * <code>repeated string callbackText = 1;</code>
     */
    com.google.protobuf.ByteString
        getCallbackTextBytes(int index);
  }
  /**
   * <pre>
   *sample message callback
   * </pre>
   *
   * Protobuf type {@code TestMessages.CallbackResponse}
   */
  public  static final class CallbackResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMessages.CallbackResponse)
      CallbackResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CallbackResponse.newBuilder() to construct.
    private CallbackResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallbackResponse() {
      callbackText_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallbackResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                callbackText_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              callbackText_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          callbackText_ = callbackText_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_CallbackResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_CallbackResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse.class, io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse.Builder.class);
    }

    public static final int CALLBACKTEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList callbackText_;
    /**
     * <code>repeated string callbackText = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCallbackTextList() {
      return callbackText_;
    }
    /**
     * <code>repeated string callbackText = 1;</code>
     */
    public int getCallbackTextCount() {
      return callbackText_.size();
    }
    /**
     * <code>repeated string callbackText = 1;</code>
     */
    public java.lang.String getCallbackText(int index) {
      return callbackText_.get(index);
    }
    /**
     * <code>repeated string callbackText = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCallbackTextBytes(int index) {
      return callbackText_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < callbackText_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, callbackText_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < callbackText_.size(); i++) {
          dataSize += computeStringSizeNoTag(callbackText_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCallbackTextList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse)) {
        return super.equals(obj);
      }
      io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse other = (io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse) obj;

      boolean result = true;
      result = result && getCallbackTextList()
          .equals(other.getCallbackTextList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCallbackTextCount() > 0) {
        hash = (37 * hash) + CALLBACKTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getCallbackTextList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *sample message callback
     * </pre>
     *
     * Protobuf type {@code TestMessages.CallbackResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMessages.CallbackResponse)
        io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_CallbackResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_CallbackResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse.class, io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse.Builder.class);
      }

      // Construct using io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        callbackText_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.internal_static_TestMessages_CallbackResponse_descriptor;
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse getDefaultInstanceForType() {
        return io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse.getDefaultInstance();
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse build() {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse buildPartial() {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse result = new io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          callbackText_ = callbackText_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.callbackText_ = callbackText_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse) {
          return mergeFrom((io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse other) {
        if (other == io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse.getDefaultInstance()) return this;
        if (!other.callbackText_.isEmpty()) {
          if (callbackText_.isEmpty()) {
            callbackText_ = other.callbackText_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCallbackTextIsMutable();
            callbackText_.addAll(other.callbackText_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList callbackText_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCallbackTextIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          callbackText_ = new com.google.protobuf.LazyStringArrayList(callbackText_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCallbackTextList() {
        return callbackText_.getUnmodifiableView();
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public int getCallbackTextCount() {
        return callbackText_.size();
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public java.lang.String getCallbackText(int index) {
        return callbackText_.get(index);
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCallbackTextBytes(int index) {
        return callbackText_.getByteString(index);
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public Builder setCallbackText(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCallbackTextIsMutable();
        callbackText_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public Builder addCallbackText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCallbackTextIsMutable();
        callbackText_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public Builder addAllCallbackText(
          java.lang.Iterable<java.lang.String> values) {
        ensureCallbackTextIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, callbackText_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public Builder clearCallbackText() {
        callbackText_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callbackText = 1;</code>
       */
      public Builder addCallbackTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCallbackTextIsMutable();
        callbackText_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestMessages.CallbackResponse)
    }

    // @@protoc_insertion_point(class_scope:TestMessages.CallbackResponse)
    private static final io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse();
    }

    public static io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallbackResponse>
        PARSER = new com.google.protobuf.AbstractParser<CallbackResponse>() {
      public CallbackResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CallbackResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallbackResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CallbackResponse> getParserForType() {
      return PARSER;
    }

    public io.github.ppissias.xsrpcj.example.performance.TestMessages.CallbackResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMessages_MessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMessages_MessageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMessages_MessageResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMessages_MessageResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMessages_CallbackResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMessages_CallbackResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TestMessages.proto\022\014TestMessages\"@\n\016Me" +
      "ssageRequest\022\023\n\013requestData\030\001 \001(\t\022\031\n\021num" +
      "berOfCallbacks\030\002 \001(\005\"{\n\017MessageResponse\022" +
      "<\n\010response\030\001 \001(\0162*.TestMessages.Message" +
      "Response.responseEnum\"*\n\014responseEnum\022\014\n" +
      "\010ACCEPTED\020\000\022\014\n\010REJECTED\020\001\"(\n\020CallbackRes" +
      "ponse\022\024\n\014callbackText\030\001 \003(\tB@\n-io.github" +
      ".ppissias.xsrpcj.example.performanceB\014Te" +
      "stMessages\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestMessages_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestMessages_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMessages_MessageRequest_descriptor,
        new java.lang.String[] { "RequestData", "NumberOfCallbacks", });
    internal_static_TestMessages_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TestMessages_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMessages_MessageResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_TestMessages_CallbackResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TestMessages_CallbackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMessages_CallbackResponse_descriptor,
        new java.lang.String[] { "CallbackText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
